language: swift
osx_image: xcode9
xcode_project: PusherChatkit.xcworkspace
xcode_scheme: PusherChatkit

script:
  - xcodebuild clean build test -project PusherChatkit.xcworkspace -scheme PusherChatkit