language: swift
osx_image: xcode9
xcode_project: PusherChatkit.xcworkspace
xcode_scheme: PusherChatkit

script:
  - xcodebuild clean build -workspace PusherChatkit.xcworkspace -scheme PusherChatkit -quiet